import uuid
from io import BytesIO
from pathlib import Path
from typing import Optional

from fastapi import HTTPException, UploadFile, status
from PIL import Image, ImageOps, UnidentifiedImageError

# --- STORAGE SETTINGS ---
# app/services/storage.py -> parents[1] is the 'app' folder
STATIC_DIR = Path(__file__).resolve().parents[1] / "static"
AVATAR_DIR = STATIC_DIR / "avatars"

# This is the prefix the browser sees. main.py mounts the static folder under
# /api/static so it goes through the existing Vite proxy (no CORS, no mixed content).
AVATAR_URL_PREFIX = "/static/avatars"

# 2 MB is plenty for a profile picture
MAX_UPLOAD_BYTES = 2 * 1024 * 1024
CHUNK_SIZE = 64 * 1024

# We accept these on the way IN, but always save as JPEG
ALLOWED_FORMATS = {"JPEG", "PNG", "WEBP"}

# Final size of the stored avatar (square)
AVATAR_SIZE = (512, 512)
JPEG_QUALITY = 85

# Anti "decompression bomb": a 10.000 x 10.000 px PNG is only a few KB zipped
# but explodes into gigabytes of RAM when decoded. Pillow refuses above this.
Image.MAX_IMAGE_PIXELS = 40_000_000


def _ensure_dir() -> None:
    AVATAR_DIR.mkdir(parents=True, exist_ok=True)


async def _read_capped(upload: UploadFile) -> bytes:
    """
    Read the upload in chunks and bail out the moment it goes over the limit.
    We never call .read() without a cap, otherwise a big file could eat all our RAM.
    """
    buffer = BytesIO()
    size = 0

    while True:
        chunk = await upload.read(CHUNK_SIZE)
        if not chunk:
            break

        size += len(chunk)
        if size > MAX_UPLOAD_BYTES:
            raise HTTPException(
                status_code=status.HTTP_413_CONTENT_TOO_LARGE,
                detail="Image is too large. Maximum size is 2MB."
            )
        buffer.write(chunk)

    if size == 0:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    return buffer.getvalue()


async def save_avatar(upload: UploadFile, old_url: Optional[str] = None) -> str:
    """
    Validates, normalizes and stores a profile picture.
    Returns the public URL path to save in the database.

    We deliberately ignore the filename and the content-type the browser sends us,
    because both are trivially faked. The only thing we trust is whether Pillow
    can actually decode the bytes as an image.
    """
    raw = await _read_capped(upload)

    # 1. Is this really an image? verify() consumes the object, so we reopen after.
    try:
        probe = Image.open(BytesIO(raw))
        probe.verify()
        image_format = probe.format
    except (UnidentifiedImageError, OSError, Image.DecompressionBombError):
        raise HTTPException(
            status_code=400,
            detail="That file is not a valid image. Please upload a JPG, PNG or WebP."
        )

    # 2. Whitelist the format. SVG never gets here (Pillow can't decode it) and that
    # is exactly what we want, since an SVG served from our own domain can run JS.
    if image_format not in ALLOWED_FORMATS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported image format '{image_format}'. Use JPG, PNG or WebP."
        )

    # 3. Re-open for the real work and normalize it
    try:
        image = Image.open(BytesIO(raw))
        # Phones store rotation in EXIF instead of rotating the pixels
        image = ImageOps.exif_transpose(image)
        # JPEG can't hold transparency, so flatten to RGB
        image = image.convert("RGB")
        # Center-crop to a perfect square so the CSS circle never squashes a face
        image = ImageOps.fit(image, AVATAR_SIZE, method=Image.Resampling.LANCZOS)
    except (OSError, Image.DecompressionBombError):
        raise HTTPException(status_code=400, detail="Could not process that image.")

    # 4. Save it. The filename is generated by US (uuid4), never taken from the
    # client, so there is no way to path traverse out of the avatars folder.
    _ensure_dir()
    filename = f"{uuid.uuid4().hex}.jpg"

    # Re-encoding as a fresh JPEG also throws away all EXIF metadata,
    # so we don't accidentally publish the GPS coordinates of someone's home.
    image.save(AVATAR_DIR / filename, format="JPEG", quality=JPEG_QUALITY, optimize=True)

    # 5. Clean up the picture they had before, so the disk doesn't fill up with orphans
    if old_url:
        delete_avatar(old_url)

    return f"{AVATAR_URL_PREFIX}/{filename}"


def delete_avatar(url: Optional[str]) -> None:
    """
    Removes a stored avatar file. Silently ignores anything we didn't store
    ourselves (external URLs, empty values, already deleted files).
    """
    if not url or not url.startswith(f"{AVATAR_URL_PREFIX}/"):
        return

    filename = Path(url).name
    target = AVATAR_DIR / filename

    # Paranoia check: make sure the resolved path is really inside our folder
    try:
        target = target.resolve()
        if target.parent != AVATAR_DIR.resolve():
            return
        target.unlink(missing_ok=True)
    except OSError:
        # A failed cleanup should never break the user's request
        pass
