"""Add location_id to entry_logs

Revision ID: 180effb51689
Revises: e24b08b636e5
Create Date: 2026-06-26 01:32:01.156466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180effb51689'
down_revision: Union[str, Sequence[str], None] = 'e24b08b636e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_logs', sa.Column('location_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('entry_logs_user_id_fkey'), 'entry_logs', type_='foreignkey')
    op.drop_constraint(op.f('entry_logs_worker_id_fkey'), 'entry_logs', type_='foreignkey')
    op.create_foreign_key(None, 'entry_logs', 'gym_locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entry_logs', 'users', ['worker_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entry_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry_logs', type_='foreignkey')
    op.drop_constraint(None, 'entry_logs', type_='foreignkey')
    op.drop_constraint(None, 'entry_logs', type_='foreignkey')
    op.create_foreign_key(op.f('entry_logs_worker_id_fkey'), 'entry_logs', 'users', ['worker_id'], ['id'])
    op.create_foreign_key(op.f('entry_logs_user_id_fkey'), 'entry_logs', 'users', ['user_id'], ['id'])
    op.drop_column('entry_logs', 'location_id')
    # ### end Alembic commands ###
