"""add requires_weight to exercises

Revision ID: a47bf74af589
Revises: 541e9bffbeab
Create Date: 2026-07-29 18:47:37.047004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47bf74af589'
down_revision: Union[str, Sequence[str], None] = '541e9bffbeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('requires_weight', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'requires_weight')
    # ### end Alembic commands ###
