"""Add worker_id to entry_logs for manual overrides

Revision ID: b2019141c04b
Revises: 6001b592652e
Create Date: 2026-06-16 01:18:56.014143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2019141c04b'
down_revision: Union[str, Sequence[str], None] = '6001b592652e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_logs', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry_logs', 'users', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry_logs', type_='foreignkey')
    op.drop_column('entry_logs', 'worker_id')
    # ### end Alembic commands ###
