"""Add tier to SubscriptionPlan

Revision ID: b25abfb4dd06
Revises: a91b47d6e0c2
Create Date: 2026-08-10 20:28:06.873718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25abfb4dd06'
down_revision: Union[str, Sequence[str], None] = 'a91b47d6e0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- 1. ADD THE COLUMN ---
    # server_default is what fills the existing rows; without it this ALTER TABLE
    # would fail on a non-empty table because the column is NOT NULL.
    op.add_column('subscription_plans', sa.Column('tier', sa.String(), server_default='Standard', nullable=False))

    # --- 2. BACKFILL FROM THE PLAN NAMES ---
    # Before this column existed, the member pricing page picked its styling by
    # string-matching the plan NAME. We reproduce that mapping here so no live plan
    # changes appearance the moment the migration runs.
    #
    # Order matters: the old frontend checked gold/pro BEFORE vip/premium, so a plan
    # called "Gold VIP" rendered as the amber Pro card. Running Pro first and then
    # limiting VIP to rows still on 'Standard' preserves that precedence.
    op.execute(
        """
        UPDATE subscription_plans
           SET tier = 'Pro'
         WHERE lower(name) LIKE '%gold%'
            OR lower(name) LIKE '%pro%'
        """
    )
    op.execute(
        """
        UPDATE subscription_plans
           SET tier = 'VIP'
         WHERE tier = 'Standard'
           AND (lower(name) LIKE '%vip%' OR lower(name) LIKE '%premium%')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'tier')
    # ### end Alembic commands ###
