"""Add action_type to entry_logs

Revision ID: db688538626e
Revises: 5b870d7c0926
Create Date: 2026-08-03 17:40:51.765359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db688538626e'
down_revision: Union[str, Sequence[str], None] = '5b870d7c0926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_logs', sa.Column('action_type', sa.String(), server_default="ENTRY" , nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry_logs', 'action_type')
    # ### end Alembic commands ###
