"""Add missing GymLocation and SubscriptionRule tables

Revision ID: e24b08b636e5
Revises: b2019141c04b
Create Date: 2026-06-26 01:10:54.428313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24b08b636e5'
down_revision: Union[str, Sequence[str], None] = 'b2019141c04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_24_7', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_locations_id'), 'gym_locations', ['id'], unique=False)
    op.create_index(op.f('ix_gym_locations_name'), 'gym_locations', ['name'], unique=True)
    op.create_table('plan_locations',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['gym_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'location_id')
    )
    op.create_table('subscription_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('allowed_time_start', sa.Time(), nullable=True),
    sa.Column('allowed_time_end', sa.Time(), nullable=True),
    sa.Column('allowed_days', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_index(op.f('ix_subscription_rules_id'), 'subscription_rules', ['id'], unique=False)
    op.drop_constraint(op.f('user_subscriptions_user_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.create_foreign_key(op.f('user_subscriptions_user_id_fkey'), 'user_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_subscription_rules_id'), table_name='subscription_rules')
    op.drop_table('subscription_rules')
    op.drop_table('plan_locations')
    op.drop_index(op.f('ix_gym_locations_name'), table_name='gym_locations')
    op.drop_index(op.f('ix_gym_locations_id'), table_name='gym_locations')
    op.drop_table('gym_locations')
    # ### end Alembic commands ###
