"""Add is_active to SubscriptionPlan

Revision ID: f2ff9bb4e594
Revises: 180effb51689
Create Date: 2026-07-04 21:54:13.402621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ff9bb4e594'
down_revision: Union[str, Sequence[str], None] = '180effb51689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'is_active')
    # ### end Alembic commands ###
