"""Add stripe_subscription_id to user_subscriptions

Revision ID: fa669f5fb516
Revises: db688538626e
Create Date: 2026-08-08 00:22:59.133433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa669f5fb516'
down_revision: Union[str, Sequence[str], None] = 'db688538626e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_column('user_subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###
